### ISSUE TITLE
Beward modbus tcp

### ISSUE THREAD

**Issue by conrad66** [Limych/ha-beward#1]
Добрый день, 
вызывная панель beward поддерживает протокол modbus tcp.
Почему бы это не использовать в связке с НА ?

**Comment by Limych** [comment]
Поясните, пожалуйста, для каких целей вы хотите использовать Modbus в данном случае.

**Comment by conrad66** [comment]
Извините, я досконально ваш код не изучал.
По modbus можно получить нажатие кнопки вызова и сигнал детектора движения.
Ну и ряд других значений согласно описанию беварда.
Если вы считаете что это лишнее, то я не настаиваю, просто предложил.

**Comment by Limych** [comment]
Я Вас ни в чём не обвиняю. Мне была непонятна Ваша мысль и я лишь попросил рассказать её подробнее.

Сейчас интеграция полностью отслеживает состояния кнопки и детектора движения. Именно они транслируются в состояния одноимённых сенсоров binary_sensor.

Modbus в данном случае обладает несколькими недостатками, из-за которых не стоит применять его.
Во-первых, этот протокол по-умолчанию выключен. Его надо особо включать в настройках.
Во-вторых, протокол является асимметричным. В нём есть один ведущий хост, а все остальные ведомые. Все сеансы связи всегда начинает только ведущий. Камера не может передать изменение состояния своего датчика (кнопка, движение). А HA для отслеживания приходится делать множество запросов. Более одного в секунду, чтобы не пропустить нажатия кнопки.
Один запрос - это 6 пакетов TCP (если правильно помню): два на установление связи, один с данными туда, один обратно, два на завершение.
Два сенсора - это два запроса. Один на кнопку, один на движение.
Итого мы имеем не менее 12 пакетов TCP на каждую камеру в секунду.
Для современных сетей это не много, конечно. Но всё же может быть неприятно, если камер несколько.
А если камера стоит удалённо на слабом канале? Например, на даче с плохой связью через GSM-модем...

Сейчас в интеграции реализован значительно более экономичный по трафику метод связи. Плюс он лучше защищён от потери передачи событий.
