### ISSUE TITLE
Support to Beward DK103M Analog to SIP Converter

### ISSUE THREAD

**Issue by yuvalg72** [Limych/ha-beward#10]
Hello, First of all, 
Thank you for developing this component. 

I live in a building that each apartment has an Intercom, I think that the the intercom is broadcast analogical and I want to use the place that Intercom apparment is located to put there a 10'' android tablet for HA Control.
(The model of the Intercom is Urmet Arco),
Photo is attached:
![IMG_20201109_205133](https://user-images.githubusercontent.com/16966257/99145923-bd147700-267b-11eb-91be-84535844a38a.jpg)

I removed the intercom apartment unit from the wall and this what I found:
![IMG_20201109_203320](https://user-images.githubusercontent.com/16966257/99145940-fa790480-267b-11eb-8518-c1a2fca80aa6.jpg)

I did a lot of research about convert an analog intercom broadcast to SIP and I found that the Beward DK103M is a perfect solution for this situation,
Link to the item:
English:
https://www.beward.cn/analog-to-ip-sip/
Russian:
https://www.beward.ru/katalog/ip-videodomofony/konvertery/ip-portal-dk103m/

I will very appreciate that if you will please add support to Beward DK103M.

Best Regards my dear friend, 
Yuval

**Comment by Limych** [comment]
Judging by the user instructions for this device, it is no different from ordinary Beward intercoms. The only difference is that the image is taken from an external source.

If so, my integration should work seamlessly with this device. Just need to register its ID in the library. But the ID itself can only be discovered when someone tries to connect — the integration will generate an error about an unknown device and indicate its ID.
