### ISSUE TITLE
Support for german ALP-600, which is a DS06M & DSXXXP3L

### ISSUE THREAD

**Issue by mcmuller** [Limych/ha-beward#17]
## Is your feature request related to a problem? Please describe.

HA stops the setup with:
Beward device Initialization Failure
Error: Unknown device "ALP-600"
Please contact the developers of the Beward library to solve this problem.

## Describe the solution you'd like

Support for this OEM-Device, sold in Germany through [https://www.alphago.de/ip-video-tuersprechanlage](url)

## Describe alternatives you've considered

...or point me to where in the code I can try to add

## Additional context

I think, this one is quite popular in Germany, as is HA. This firmware-variant comes without MODBUS-support, if this is relevant.

Output of /cgi-bin/systeminfo_cgi?action=get

`HostName=ALP-600
ChannelNum=1
Standard=PAL
DeviceID=721758
SoftwareVersion=3.1.14.0.6.18.63
WebVersion=ALP-Web-UI-V.40
HardwareVersion=Hi3518 IP Camera
DeviceModel=ALP-600
DeviceUUID=Iv51lnOfNSvyzZOG0QRj2eRjrrM8HUyf
FaceRecognition=1
UpTime=15.10:18:55`

**Comment by Limych** [comment]
Added at https://github.com/Limych/py-beward/releases/tag/1.1.4
