### ISSUE TITLE
broken after HA update to 2022.7.0 (python3.10 intruduced)

### ISSUE THREAD

**Issue by mcmuller** [Limych/ha-beward#19]
## Version of the component

Version:

1.1.18

## Describe the bug

fails to start after HA update to 2022.7.0

## To Reproduce
This is the configuration I used:
beward:
  - host: 192.168.1.21
    username: "xxxxx"
    password: "xxxxxxx"
    binary_sensors:
        - online
        - motion
        - ding
    sensors:
        - last_activity
        - last_motion
        - last_ding

Add your configs here.

```

## Debug log
<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->
```text

Add your logs here.

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 07:53:41 (1 occurrences)
Last logged: 07:53:41

Setup failed for custom integration beward: Requirements for beward not found: ['av~=8.0'].

## Expected behavior

normal start

## Additional context

if you need additional log, please let me know. I guess it's about the recent python 3.10 update in HA

**Comment by booroondook-eng** [comment]
The same is for me.

**Comment by gshlomi** [comment]
Same here
