### ISSUE TITLE
New version (1.1.21) has the same bug as 1.1.18

### ISSUE THREAD

**Issue by booroondook-eng** [Limych/ha-beward#21]
**Environment**

- Home Assistant Core release with the issue: 2022.7.2
- This custom component release with the issue: 1.1.21
- Last working this custom component release (if known): HA 2022.6, Beward 1.1.18
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervisor 2022.07.0, Frontend 20220707.0

**Describe the bug**
  Beward Intergation does not start

**Debug log**
```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 12:23:36 (1 occurrences)
Last logged: 12:23:36
Setup failed for custom integration beward: Requirements for beward not found: ['av~=8.0'].
```

**Additional context**
![2022-07-10 12_20_49-Window](https://user-images.githubusercontent.com/8210458/178139053-dd025b79-1e0c-4626-93dd-7ef490ff7493.png)
![2022-07-10 12_23_40-Window](https://user-images.githubusercontent.com/8210458/178139056-c69434ff-8100-43b9-88c6-5836a2e0bb98.png)
![2022-07-10 12_26_02-Window](https://user-images.githubusercontent.com/8210458/178139057-23b88bcd-b674-4b22-944d-e552b7a4f3d2.png)
![2022-07-10 12_26_35-Window](https://user-images.githubusercontent.com/8210458/178139058-ea314ebf-c3fe-4c8f-9df9-354cabf0954e.png)

**Comment by 007lessi** [comment]
It's the same with me.

**Comment by Limych** [comment]
Thanks :heart: 

Fixed at v1.1.22: https://github.com/Limych/ha-beward/releases/tag/1.1.22

**Comment by 007lessi** [comment]
It also does not work on version 1.1.22.
`Logger: homeassistant.setup
Source: setup.py:162
First occurred: 22:12:09 (1 occurrences)
Last logged: 22:12:09

Setup failed for custom integration beward: Requirements for beward not found: ['av~=9.2'].`

**Comment by booroondook-eng** [comment]
The same for me
```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 20:06:01 (1 occurrences)
Last logged: 20:06:01
Setup failed for custom integration beward: Requirements for beward not found: ['av~=9.2'].
```

**Comment by Limych** [comment]
:(

**Comment by Limych** [comment]
Made a new attempt to fix this bug. If it doesn’t help, I don’t even know what to do next — everything works like clockwork in my tests.

https://github.com/Limych/ha-beward/releases/tag/1.1.23

**Comment by booroondook-eng** [comment]
1.1.23 - the same error:
```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 11:33:53 (1 occurrences)
Last logged: 11:33:53

Setup failed for custom integration beward: Requirements for beward not found: ['ha-av~=9.2'].
```

**Comment by Limych** [comment]
I have no idea how to fix it. `ha-av` is officiall library for HA:
* https://github.com/home-assistant/core/blob/f6fd7d115e6813d7980a6521919e0021f6415b94/requirements_all.txt#L786
* https://github.com/home-assistant/core/blob/f6fd7d115e6813d7980a6521919e0021f6415b94/homeassistant/components/generic/manifest.json#L5
* https://github.com/home-assistant/core/blob/f6fd7d115e6813d7980a6521919e0021f6415b94/homeassistant/components/stream/manifest.json#L5

**Comment by mcmuller** [comment]
same error here with 1.1.23. As @Limych  has no problems, maybe some leftovers in our installs? But even with erasing beward: from config and manual delete of instaled files - same same :-(

**Comment by booroondook-eng** [comment]
Sorry for my language... I'll speak from my heart :-) in Russian.
Андрей, ситуация, насколько я понимаю, сводится к "угадыванию" правильной версии ha-av для прописывания ее в манифесте.
Короче, если оставляем "ha-av~=9.2" или, как было раньше, "av~=8.0", то вылезает вышеописанная ошибка, и интеграция не работает. Все сенсоры становятся недоступными и т.д. Если удалить интеграцию (не в HACS, а в "Интеграциях", а затем попытаться добавить ее снова, то ничего не выходит - сразу же выдается ошибка, не давая даже ввести начальные данные
Если же прописать не "ha-av~=9.2", а "ha-av==10.0.0b4", то после рестарта ХА ошибка не вылезает, но однако и интеграция не работает (все объекты недоступны). После удаления и нового добавления интеграции сходу кажется, что все нормально - дает ввести реквизиты, указать опции и даже сохранить. Но... при этом объекты камеры вообще не создаются, а "тревожные" и прочие объекты хоть и создаются, но недоступны.

P.S. Еще раз извиняюсь за русский, просто на английском я так подробно не смог бы изложить.
P.P.S. Последняя буква моего никнейма появилась много лет назад и никаких смысловых ассоциаций не несет.

**Comment by Limych** [comment]
Ну наконец-то нормальный русский язык! :)

Проблема в том, что на тестовой сборке на любой версии HA всё работает отлично. Но то тестовая сборка. Там HA поставлен с нуля.

Вторая проблема, что официально версии av выше 9.2 ещё не опубликовано. Да, есть десятая. И да, она используется в HA 2022.8.0 но то пока ещё две беты. :-/

Единственное, что сейчас вижу как путь решения — это прописать в зависимостях или "ha-av==9.2" или "ha-av>=9.2". Но я не могу проверить работоспособность этих вариантов, так как у меня всё работает нормально.

Надежда только на вас...

**Comment by 007lessi** [comment]
> Ну наконец-то нормальный русский язык! :)
> 
> Проблема в том, что на тестовой сборке любой версии HA всё работает отлично. Но то тестовая сборка. Там HA поставлен с нуля.
> 
> Вторая проблема, что официально версия av выше 9.2 ещё не опубликовано. Да, есть десятая. И да, используется в HA 2022.8.0, но то пока ещё две беты. :-/
> 
> Единственное, что сейчас вижу как пути решения — это прописать в зависимостях или "ha-av==9.2" или "ha-av>=9.2". Но я не могу проверить работоспособность вариантов, так как у меня всё работает нормально.
> 
> Надежда только на вас...



Что нужно сделать?

**Comment by Limych** [comment]
Ничего сложного.

Попробовать в `manifest.json` изменить упомянутую строчку и посмотреть, что будет, перезапуская систему.

**Comment by mcmuller** [comment]
changed ha-av>=9.2 in maifest.json. It's building fine now and setting up sensors, but no cameras. Action is not triggered by sensors.

**Comment by 007lessi** [comment]
> Ничего сложного.
> 
> Попробовать в `manifest.json` изменить упомянутую строчку и посмотреть, что будет, перезапуская систему.

Поменял на значение "ha-av>=9.2" - заработало на версии Home Assistant 2022.7.3

**Comment by booroondook-eng** [comment]
> Поменял на значение "ha-av>=9.2" - заработало на версии Home Assistant 2022.7.3

Рано радуемся. С такой конфигурацией объекты типа "камера" недоступны, а остальные датчики в состоянии "неизвестно". 
![2022-07-11 19_57_50-Window](https://user-images.githubusercontent.com/8210458/178318245-f030c210-c187-408b-aa93-226c8f240555.png)
Ну а если глянуть в лог, то там такое:
```
Logger: homeassistant.components.camera
Source: custom_components/beward/__init__.py:316
Integration: Камера (documentation, issues)
First occurred: 19:55:06 (1 occurrences)
Last logged: 19:55:06

Error while setting up beward platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/beward/camera.py", line 71, in async_setup_entry
    entities.extend(await _async_setup_entities(controller, config))
  File "/config/custom_components/beward/camera.py", line 98, in _async_setup_entities
    entities.append(BewardFileCamera(controller, camera_type))
  File "/config/custom_components/beward/camera.py", line 197, in __init__
    controller.history_image_path(CAMERAS[camera_type][2]),
  File "/config/custom_components/beward/__init__.py", line 316, in history_image_path
    return self.hass.config.path(self.hass.config.media_dirs[DOMAIN], file_name)
KeyError: 'beward'
```

**Comment by booroondook-eng** [comment]
Ну, как я понял, на эту интеграцию можно забивать - просвета не будет. Или есть надежда?

**Comment by Limych** [comment]
Интересный вопрос.

Так прям и напрашивается спросить в ответ: а что, Вам кто-то здесь что-то должен? Чем лично Вы помогли проекту разобраться в проблеме и решить её? Вы изучили код и нашли причину?..

Когда у меня будет время и желание, я решу проблему. Если кто пришлёт PR с решением раньше этого, я буду ему благодарен.

**Comment by booroondook-eng** [comment]
Пардон, но где вы узрели в моих словах какие-либо требования или даже просьбы?
Я лишь спросил - имеет ли смысл удалить эту интеграцию из ХА и забыть про неё. Или же можно на что-то надеяться.
Вас никто ни к чему не обязывает - не дай бог!
Просто напишите - проект закрыт, всем пока.  И все всё поймут. Не забудьте также удалить проект из HACS'а, чтобы не вводить пользователей в заблуждение.
А то на данный момент остаётся какая-то "подвешенная" ситуация. А это хуже всего.

**Comment by Limych** [comment]
Когда проект будет закрыт, я напишу.

**Comment by mcmuller** [comment]
...if you need some logs or testing, please drop a note here.

**Comment by Limych** [comment]
Another attempt to fix this error. But I'm not sure if this will help...

**Comment by mcmuller** [comment]
just installed and looks fine! I get cams and sensors and no log error/warnings! Seems you got it!

**Comment by Limych** [comment]
Thanks for feedback ❤️ 

This update contains a potential issue.  When a new version of `ha-av` library is released, it may not be compatible.  And everything breaks again...

**Comment by booroondook-eng** [comment]
Работает! Огромное спасибо разработчику!
