### ISSUE TITLE
1.1.25 is throwing error

### ISSUE THREAD

**Issue by mcmuller** [Limych/ha-beward#25]
**Environment**

- Home Assistant Core release with the issue: 2022.7.6
- This custom component release with the issue: 1.1.25
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): HomeAssistant VM on Freenas

**Describe the bug**

any idea? It is working, so not too serious in the moment.

**Log**

Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 12:58:47 (143 occurrences)
Last logged: 17:42:37

`Exception in _update_callback when dispatching 'beward_update_721758': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 397, in state if value.tzinfo is None: AttributeError: 'str' object has no attribute 'tzinfo' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/beward/sensor.py", line 144, in _update_callback self.async_schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 677, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state state = self._stringify_state(available) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 408, in state raise ValueError( ValueError: Invalid datetime: sensor.beward_721758_last_motion has timestamp device class but provides state 2022-07-25T17:35:28+01:00:<class 'str'> resulting in ''str' object has no attribute 'tzinfo''`

**Comment by mcmuller** [comment]
further observation: after one or two ring (ding) events, the adapter stops working, showing above error in logs

**Comment by asafhas** [comment]
@mcmuller - I saw a similar problem with "last ding" sensor.
Try adding this as a workaround, in sensor.py line 142 (before calling async_schedule_update_ha_state):

if self._sensor_type == SENSOR_LAST_MOTION:
    self._attr_native_value = datetime.strptime(self._attr_native_value, '%Y-%m-%dT%H:%M:%S%z')

**Comment by Limych** [comment]
Fixed at 414d4166b91866333dfe4bb32aa6de1c9b7259d2
