### ISSUE TITLE
Tryin got install but getting component error

### ISSUE THREAD

**Issue by includes08** [Limych/ha-beward#6]
Configuration invalid
Component error: beward - cannot import name 'DOMAIN' from 'custom_components.beward' (/config/custom_components/beward/__init__.py)

if you need any information let me know

**Comment by Limych** [comment]
Please, update component to latest version. Sorry o:-)

**Comment by Sergbmw** [comment]
> Please, update component to latest version. Sorry o:-)

после вчерашнего обновления опять стала эта ошибка

**Comment by Limych** [comment]
Хм-м...
